# Generated by Django 3.0.14 on 2022-07-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '게시글', 'verbose_name_plural': '게시글'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
