# Generated by Django 3.0.14 on 2022-07-23 09:47

from django.db import migrations, models
import instagram.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to=instagram.models.uuid_name_upload_to)),
                ('is_public', models.BooleanField(default=False, verbose_name='공개여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instagram 게시글',
                'verbose_name_plural': 'Instagram 게시글',
                'db_table': 'instagram_post',
            },
        ),
    ]
