# Generated by Django 3.0.14 on 2022-07-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20220724_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='InstagramPostComment',
        ),
    ]
