# Generated by Django 3.0.14 on 2022-07-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_instagrampost_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
