# Generated by Django 3.0.14 on 2022-07-24 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0003_auto_20220724_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagrampostcomment',
            options={'verbose_name': 'instagram 게시글 댓글', 'verbose_name_plural': 'instagram 게시글 댓글'},
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
