# Generated by Django 3.0.14 on 2022-07-23 09:23

from django.db import migrations, models
import utils.media_lib


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_instagrampost_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='photo',
            field=models.ImageField(blank=True, upload_to=utils.media_lib.uuid_name_upload_to),
        ),
    ]
